### ISSUE TITLE
About F1 problem (Found input variables without list of list)

### ISSUE THREAD

**Issue by WinniyGD** [shivaat/MTLB-STRUCT#1]
When I runed your codes, it raised TypeError:

`raise TypeError('Found input variables without list of list.')
TypeError: Found input variables without list of list.`

The bug may be located in berteval.py (line 117).

` fscore = f1_score(valid_tags, pred_tags)`

![image](https://user-images.githubusercontent.com/70563473/100515974-55057b00-31bb-11eb-834e-21b8118580f4.png)

**Comment by shivaat** [comment]
Hi WinnyGD,
Thanks for raising the issue. I think it has to do with some change in the new versions of seqeval framework. I'll try to solve it today or tomorrow.

**Comment by WinniyGD** [comment]
OK, Thanks!

**Comment by WinniyGD** [comment]
OK! Thank~
It is highly recommended that you upload your requirements.txt.
I can know what version you use.

**Comment by shivaat** [comment]
All done!

**Comment by WinniyGD** [comment]
Good Job！
